### PR TITLE
Added buble and ran some tests

### PR DESCRIPTION
**Pull request by Akkuma**
I added in buble, ran in sauce and Chrome. I'll have Safari and Firefox committed shortly.

### CODE REVIEW

**Comment by kpdecker** [comment]
Could you rebase without the data.json change? I run everything on the same machine at the same time to try to isolate as much as possible and maintain some level of consistency.

**Comment by Akkuma** [comment]
Sure thing!

**Comment by Akkuma** [comment]
This should be good to go now.

**Comment by kpdecker** [comment]
Thanks! Will run the updates now.

**Pull request merged**
